#!/bin/bash
read -p "любой предмет " name
if grep -i "$name" for_programmer; then
echo "Этот предмет нужен для поступения на программиста"
else
echo "Этот предмет не нужен для поступления на программиста"
fi
